enableScripts: true

nodeLinker: node-modules

plugins:
  - checksum: 47d886a00e471a164c6a44aa71fc84c09b96fdb45b11641544f63ab7b6009ace67f4861f3bd282c2e72a5e47e35988cbf621de700b846b1b6c399bfbb0b10877
    path: .yarn/plugins/yarn-plugin-echoscript.cjs
    spec: "https://raw.githubusercontent.com/taeyoon0137/echoscript/main/packages/plugin/plugin/bundle.js"
