/*
  Copyright 2022. Taeyoon Lee.
  All rights reserved
*/

import Head from 'next/head';
import Image from 'next/image';
import styled, { createGlobalStyle } from 'styled-components';

/**
 * ### 이력서 페이지
 *
 * 이력서를 표시하는 페이지입니다.
 *
 * _해당 페이지는 현재 홈 페이지로 기능합니다._
 *
 * @component
 */
const Resume = () => {
  return (
    <>
      <Head>
        <title>Taeyoon Dot.</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <BackgroundStyle />
      <Styled.Main>
        <Styled.Resume>
          <Image src='/vercel.svg' alt='Vercel Logo' width={100} height={24} priority />
        </Styled.Resume>
      </Styled.Main>
    </>
  );
};

const BackgroundStyle = createGlobalStyle`
  html {
    background-color: #F7F8F9;
  }
`;

const Styled = {
  Main: styled.main`
    flex: 1;
    align-items: center;
    padding: 80px;
  `,
  Resume: styled.section`
    width: 100%;
    max-width: 1024px;
    min-height: 2000px;
    background-color: white;
    border-radius: 8px;
    filter: drop-shadow(0px 4px 8px rgba(0, 0, 0, 0.08));
  `,
};

export default Resume;
