/*
  Copyright 2022. Taeyoon Lee.
  All rights reserved
*/

import Head from 'next/head';
import Image from 'next/image';
import styled from 'styled-components';

/**
 * ### 이력서 페이지
 *
 * 이력서를 표시하는 페이지입니다.
 *
 * _해당 페이지는 현재 홈 페이지로 기능합니다._
 *
 * @component
 */
const Resume = () => {
  return (
    <>
      <Head>
        <title>Taeyoon Dot.</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Styled.Main>
        <Image src='/vercel.svg' alt='Vercel Logo' width={100} height={24} priority />
      </Styled.Main>
    </>
  );
};

const Styled = {
  Main: styled.main``,
};

export default Resume;
